# Generated by Django 2.2.13 on 2020-09-11 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0003_arrivageexistant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrivageexistant',
            options={'ordering': ['-created'], 'verbose_name': 'Arrivage Existant', 'verbose_name_plural': 'Arrivage Existants'},
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('motif', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_sortie', to='examples.Article')),
            ],
            options={
                'verbose_name': 'Sortie',
                'verbose_name_plural': 'Sorties',
            },
        ),
    ]
